[tool.poetry]
name = "urag"
version = "v0.0.1"
description = "urag"
authors = ["WALL-AI <gaojing850063636@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.7.2"
python-dotenv = "^1.0.1"
chromadb = "0.5.3"
aiohttp = "^3.11.6"
transformers = "^4.46.3"
openai = "^1.54.5"
tiktoken = "^0.8.0"
pydantic-extra-types = "^2.10.0"
pillow = "^11.0.0"
duckduckgo-search = "^6.3.5"
llama-index-core = "^0.12.0"
bm25s = "^0.2.4"
rank-bm25 = "^0.2.2"
qdrant-client = "^1.12.1"
torch = "^2.5.1"
llmlingua = "^0.2.2"
llama-index-readers-file = "^0.4.1"
docx2txt = "^0.8"
llama-index-embeddings-huggingface = "^0.4.0"
llama-index-embeddings-openai = "^0.3.1"
jieba = "^0.42.1"
elasticsearch = "^8.17.0"
oss2 = "^2.19.1"
boto3 = "^1.35.86"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
